### ISSUE TITLE
Remove non-shortest tests from repo

### ISSUE THREAD

**Issue by slavingia** [anti-work/shortest#122]
### Why

Make it clear what shortest does without polluting the repo with other tests that people may think are shortest tests.

Bounty: $100

**Comment by martianshaan** [comment]
@slavingia  can I work on this ?

**Comment by slavingia** [comment]
Sure, just make sure you keep the shortest tests around, just remove the vitest stuff.

**Comment by m2rads** [comment]
> Apologies for multiple PR creations - was facing an issue while signing the CLA agreement

No problem. Feel free to merge the PR.
