### ISSUE TITLE
Add shortest test for creating a new shortest via shortest.com

### ISSUE THREAD

**Issue by slavingia** [anti-work/shortest#128]
Bounty: $1,000

### Why

Communicate the value and how-to-usage of Shortest within this repo in more ways.

**Comment by slavingia** [comment]
As an experiment, increased this bounty to $1,000 as it requires some product thinking. DM me on Twitter if you have any questions.

**Comment by bojl** [comment]
How can I add a repo to my shortest dashboard? 🤔

**Comment by slavingia** [comment]
Assign yourself a pr and it should show up

**Comment by slavingia** [comment]
On further thought we can delete the web app and focus on the package
