### ISSUE TITLE
Visual Testing

### ISSUE THREAD

**Issue by crabest** [anti-work/shortest#142]
### What

Add screenshot comparison for visual regression testing

### Why

When we have a design ready we can compare the results with what we have
Also while coding, it may result some visual regression, for that we can compare the images.

**Comment by crabest** [comment]
Please let me know your thoughts before I start implementing it!

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add a new method to compare screenshots and update the execute method to handle the new 'compare_screenshot' action.

You can review changes in this commit: https://github.com/jacks-sam1010/anti-work-shortest-142/commit/9c30253c436550a6e0002b249138ac9ebf96e115.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by slavingia** [comment]
Should work, probably in conjunction with caching to make tests run faster? Also, clarity on what counts as a regression. 

In theory, anything that is important can already be tested via natural language ("check every page and make sure no buttons touch") so not sure this is value-additive and may overly complicate things.

A simple section in the README explaining how to use shortest for visual regressions may be enough.

**Comment by crabest** [comment]
for the visual testing I thought of taking like screenshots before and after and comparing without the need of AI, but I think it doesn't serve the idea of giving most of the things to natural language.

**Comment by slavingia** [comment]
Ya starting with more shortest tests in this repo as examples may be a good start
