### ISSUE TITLE
[Suggestion] Video tutorials would be much appreciated 

### ISSUE THREAD

**Issue by Greatz08** [anti-work/shortest#143]
If you could provide some video tutorials, or at least one great tutorial demonstrating different scenarios in which this can be used for QA testing, it would be much appreciated by many :-))
Btw concept is great so thankyou very much for this project

**Comment by slavingia** [comment]
Would be cool! What kind of examples would you be interested in? Visual regression, business logic, complex end-to-end, or something else? Applied to a certain kind of project, or a specific one?

**Comment by slavingia** [comment]
There's already one short video, which will be added to the website and readme soon. Will make another once the other features are live.

**Comment by slavingia** [comment]
A video has been added to the README! https://github.com/anti-work/shortest

**Comment by amk-dev** [comment]
made a hello world video on how to setup shortest. if this is helpful to anyone.


https://github.com/user-attachments/assets/72ced236-ea85-4830-a6ce-2d903feacb07

**Comment by Nuzhacks** [comment]
hey I get the following error, please can you advise?
Test Execution Error: Build failed with 2 errors:
error: Failed to create output directory: mkdir C:\Users\nuzha\AppData\Local\Temp\shortest-cache\C:: The filename, directory name, or volume label syntax is incorrect.

**Comment by slavingia** [comment]
Not sure it works on Windows. Recommend a Mac or Linux if you can't debug
