### ISSUE TITLE
playwright browser installation does not consider the package manger used

### ISSUE THREAD

**Issue by amk-dev** [anti-work/shortest#144]
**How to reproduce**

1. make sure to remove playwright cache, even if you uninstall playwright, the cache may still be there
   - in mac its `~/Library/Caches/ms-playwright`
   - for other platforms check playwright the [docs](https://playwright.dev/docs/browsers#managing-browser-binaries)
2. make a new directory `shortest-test`, cd into it, init & install `@antiwork/shortest` using `pnpm`
3. create `shortest.config.ts`, here's mine
```typescript
import type { ShortestConfig } from "@antiwork/shortest";

export default {
  headless: false,
  baseUrl: "http://localhost:3000",
  testDir: "app/__tests__",
  anthropicKey: "sample-key",
} satisfies ShortestConfig;
```
4. create a sample test file `app/__tests__/helloworld.test.ts`, doesnt matter if its empty
5. run `pnpm shortest`
6. you'll get the below error screen

<img width="1444" alt="image" src="https://github.com/user-attachments/assets/3727c9df-9547-48ca-aa13-fd7eff885f06" />

I can make a PR with a fix once you guys confirms the bug. lmk.

**Comment by m2rads** [comment]
Thanks for reporting this issue. Could you please run npx playwright install in the same project directory and let me know if you see any issues!? 

If not then we can improve this by handling each package manager separately instead of using npx for all. Please let me know. Thanks

**Comment by slavingia** [comment]
Reopen once ^

**Comment by amk-dev** [comment]
hey this still happens. i'm guessing `npx` is being confused by the `node_modules` structure used by `pnpm` and giving up.

<img width="1448" alt="image" src="https://github.com/user-attachments/assets/ff0a283c-af03-41f8-b3e7-1db1959c0acc" />

---

i was exploring the codebase, so gave solving this a shot, the below solution should work. ( i tested pnpm on mac with it. incase we're going with this solution, i can do further testing and make a PR ).

Also when going through the code, saw the browser installation logic used in multiple places,

- [cli/setup.ts](https://github.com/anti-work/shortest/blob/28f02bdd7886940b77d6ab72d88d010ddbce7d88/packages/shortest/src/cli/setup.ts#L23-L32)
- [browser/manager/index.ts](https://github.com/anti-work/shortest/blob/28f02bdd7886940b77d6ab72d88d010ddbce7d88/packages/shortest/src/browser/manager/index.ts#L31-L48)

I thought this is a good opportunity to make a helper function that can be used in both places, since the logic is the same. so extracted them out to a new file.

`shortest/packages/shortest/src/utils/platform.ts`

```typescript
import { platform } from "os";

type PackageManager = "npm" | "pnpm" | "yarn";

export const getPackageManager = (): PackageManager => {
  const packageManager = process.env.npm_config_user_agent?.includes("pnpm")
    ? "pnpm"
    : process.env.npm_config_user_agent?.includes("yarn")
    ? "yarn"
    : "npm";
  return packageManager;
};

export const getInstallationCommand = (packageManager: PackageManager) => {
  const isWindows = platform() === "win32";

  const commands = {
    npm: {
      windows: "npx.cmd playwright install chromium",
      other: "npx playwright install chromium",
    },
    pnpm: {
      windows: "pnpx.cmd playwright install chromium",
      other: "pnpx playwright install chromium",
    },
    // commands for yarn, long time since i used yarn, need to look up the commands
  };

  return isWindows
    ? commands[packageManager].windows
    : commands[packageManager].other;
};
```

and this is where the code is used.

`shortest/packages/shortest/src/browser/manager/index.ts`

```typescript
if (
  error instanceof Error &&
  error.message.includes("Executable doesn't exist")
) {
  const packageManager = getPackageManager();
  const installCmd = getInstallationCommand(packageManager);

  execSync(installCmd, { stdio: "inherit" });
  console.log(pc.green("✓ Playwright browser installed"));
}

```


---

lmk your thoughts.

**Comment by slavingia** [comment]
Do those changes fix your issue?

**Comment by amk-dev** [comment]
> Do those changes fix your issue?

yup. it does. 

>  If so, worth a PR IMO

on it

**Comment by m2rads** [comment]
Hey @amk-dev please take a look at `packages/shortest/src/browser/manager`. This is where your issue is happening. Lmk if you have any questions.

**Comment by m2rads** [comment]
Also looking at the error you're getting seems like pnpm did not install playwright package along with shortest. That might happen since we label playwright as peerDependecny internally. To help troubleshoot the cause of this, please try installing playwright manually like `pnpm add playwright` and then run the shortest command again. If this issue still happens then we can implement your fix. Otherwise this might just be as simple as marking playwright as dependency when bundling our package.

**Comment by amk-dev** [comment]
Hey @m2rads 

I think the issue arrises mainly because of how `pnpm` & `npm` handles the file structure of `node_modules`. `npm` expects a flat file structure, `pnpm` doesnt have that.

> please try installing playwright manually like pnpm add playwright

this will work, because `playwright` will be installed available in `node_modules->playwright`

> Otherwise this might just be as simple as marking playwright as dependency when bundling our package.

I don't think this will work. even if it does, it is a bad idea to put `playwright` into `dependencies` instead of `peerDependencies` imo. by doing so,

* You take away complete control from the user on which playwright version they want to use. they'll have to use hacks like `pnpm` overrides if they want to change versions.
* `shortest` cannot support multiple versions of `playwright` if needed. (`peerDeps` will allow this)
* `shortest`'s user might be already using some version of `playwright`, and if you're adding `playwright` as a direct dependency of `shortest`.  It will lead to their project having multiple versions of `playwright` installed at the same time. this might lead to weired and unexpected behaviours. especially with typescript.
* also it will cause bundle size issues due to having multiple versions installed. ( this is not a practical concern for `shortest` since its not directly shipped to user's app )

imo, `peerDependencies` is the best place for `playwright` as far as `shortest` is concerned.

**Comment by slavingia** [comment]
Would it help to switch all of shortest to just using npm?

**Comment by amk-dev** [comment]
Usually in libraries, you will instruct the user to install the `peerDependencies` seperately. may be we can add this to docs. the issue here is `shortest` trying to do `npx playwright install`. instead of doing this, you can throw a warning to the user instructing them to do this manually.

**Comment by amk-dev** [comment]
would be nice to know why the `npx playwright install` code was introduced in the first place. saw it was added recently. 
apologies if this issue took all of your time.

**Comment by amk-dev** [comment]
> Would it help to switch all of shortest to just using npm?

this would solve the issues. but some people might not use `shortest` purely based on this reason ? pretty sure you'll get issues like `support pnpm`

**Comment by m2rads** [comment]
You bring up a good point @amk-dev. The key error here is `playwright: command not found`. This means that `pnpm` did not install the peerDependencies. Doing some research on this matter seems like `pnpm add --install-peer-deps @antiwork/shortest` should solve this issue. Would you be able to test this on your end? If that's the case then maybe we can just update the installation guide in the docs. 

Please make sure to uninstall playwright browsers using `npx playwright uninstall --all` for a better troubleshooting. This can help us coming up with a good solution. 

Thanks for your time on this.

**Comment by m2rads** [comment]
@amk-dev you bring up a good point about peerDependencies. The key error here is `playwright: command not found`. Even if we implement your solution, for users who use `pnpm` they still get this issue. I found a [discussion](https://news.ycombinator.com/item?id=30920611) on this on Hacker News that might be helpful. 

I think the best way to address this is to change the docs in this way: 

```shell 
pnpm add -D @antiwork/shortest
pnpm add playwright
``` 

This is a trade off between flexibility and convenience. @slavingia what do you think?

**Comment by amk-dev** [comment]
> Even if we implement your solution, for users who use pnpm they still get this issue. 

in my testing they won't.

see, pnpm install peer deps by default these days. but the structure of the node_modules is not what `npx` expects. so `npx`, wont be able to resolve `playwright` properly. so instead of `npx`, you use `pnpx` if the user is using `pnpm`, it will correctly resolve it. so user's won't get the error.

**Comment by m2rads** [comment]
Yes I agree with your point.

I'd love to try your solution. Please don't hesitate to open a PR. Or if you want I can make the changes and open a PR. Whatever works for you. 

Keep in mind that testing locally might be a bit deceiving. Just an fyi that there is a  folder `test-cli` that can be used to isolate the testing env for these stuff. But yeah it would be great to try it your way. Let me know if you need any help to setup your local env.

**Comment by slavingia** [comment]
> > Would it help to switch all of shortest to just using npm?
> 
> 
> 
> this would solve the issues. but some people might not use `shortest` purely based on this reason ? pretty sure you'll get issues from people like `support pnpm`

As long as it works with pnpm setups, which I assume it will, I think having just npm in the docs and a node_modules that reflect that would work

**Comment by amk-dev** [comment]
@m2rads 

> I'd love to try your solution. Please don't hesitate to open a PR. Or if you want I can make the changes and open a PR. Whatever works for you.

I'll get to making a PR today afternoon. ( i'm from india, and its 6AM here now ). gotta catch some sleep. 

I have one question though,
* I see there's a similar browser installation logic in `setup.ts`, should i care about that ? saw it's used in a `postinstall` script

**Comment by m2rads** [comment]
That script is used to handle playwright browser installation at the time of installing the shortest lib but seems like at the time of post installation the setup script is still not available so I implemented a safeguard in browser manager. 

I think with your solution this will become obsolete. Feel free to delete it in your PR.

**Comment by amk-dev** [comment]
Adding one more point that is not relevent to this issue, but might be interesting to explore

do you guys have a code formatting config ( prettier / anything else ), because may be my vscode did not pickup it up, and i couldnt find it in a quick search. right now for me the formatting uses my config, which seems to be different from the one you guys are using, which will add irrelevent code changes if i open a PR.

incase you guys doesn't have one, i can create a basic config. it doesnt have to be anything fancy, but having one makes sure everyone has the same formatting. helpful in code reviews.

LMK if i have to open a seperate issue to track this

**Comment by m2rads** [comment]
sounds good please track it here.

> Adding one more point that is not relevent to this issue, but might be interesting to explore
> 
> do you guys have a code formatting config ( prettier / anything else ), because may be my vscode did not pickup it up, and i couldnt find it in a quick search. right now for me the formatting uses my config, which seems to be different from the one you guys are using, which will add irrelevent code changes if i open a PR.
> 
> incase you guys doesn't have one, i can create a basic config. it doesnt have to be anything fancy, but having one makes sure everyone has the same formatting. helpful in code reviews.
> 
> LMK if i have to open a seperate issue to track this

**Comment by slavingia** [comment]
Atomic PRs are preferred so I created a new issue. 

Less cognitive load: https://minds.md/zakirullin/cognitive

And cleaner training data for future AIs and humans :)

**Comment by amk-dev** [comment]
shared this with some friends who love creating a ton of abstractions. the software world would be a better place if more people read and understood this.

**Comment by amk-dev** [comment]
hey @m2rads 
i don't have a windows PC right now, do the `npx.cmd` usage required for windows ? does just using `npx` leads to any errors ?
