### ISSUE TITLE
Can there be a video to show the function?

### ISSUE THREAD

**Issue by linyu003** [anti-work/shortest#148]
### What

we need a video to show the function of shortest

### Why

It seems that shortest has amazing functionality. However, there is no video or even image to prove it. If there can be a video show case, it will be more credible

**Comment by m2rads** [comment]
Hi @linyu003 this PR: #139 is in progress which will address your issue. Below is the video we are putting as demo.
Let me know if you'd like a more comprehensive one. Also did you try running this tool yourself?

https://github.com/user-attachments/assets/1b0134d9-7d4d-4ef5-bfef-03a52b488b87

**Comment by slavingia** [comment]
A video has been added to the README! https://github.com/anti-work/shortest
