### ISSUE TITLE
Shortest Not Running On Mac

### ISSUE THREAD

**Issue by Aldian1** [anti-work/shortest#221]
### What

I imported the project, setup test files and ran which worked. When I went to run again it hangs on the run command 
<img width="411" alt="image" src="https://github.com/user-attachments/assets/56fc8799-64ef-4a08-ac44-eacdb414ca8f" />

**Comment by Aldian1** [comment]
Have tried to debug this and bun is telling me its a package issue but not sure what as when i intially installed shortest i had no package conflcits or issues

**Comment by slavingia** [comment]
Could you try pnpm instead of bun?

**Comment by Aldian1** [comment]
<img width="942" alt="image" src="https://github.com/user-attachments/assets/8ece2eb9-5d1a-435a-93b3-60230e97b667" />

Removing everything and re-installing with bun worked ! :D

**Comment by slavingia** [comment]
Nice, if you want to add bun examples to the readme, maybe others would appreciate. and yay!
