### ISSUE TITLE
Way to test changes for green build before committing

### ISSUE THREAD

**Issue by slavingia** [anti-work/shortest#34]
, or auto revert if the changes cause the build to fail, or open new PR with head branch as the feature branch

**Comment by m2rads** [comment]
I think building a custom test runner could solve this and open many more possibilities.

**Comment by crabest** [comment]
@m2rads can you elaborate more? I don't understand the "custom test runner".

**Comment by m2rads** [comment]
@crabest I'm basically referring to a server where it's primary purpose is to execute tests and report the results. I am suggesting creating a custom test runner that would work similarly to how GitHub Actions runs tests, but with more flexibility and integration with Shortest.

**Comment by slavingia** [comment]
could also address this:

> I'll probably look at this during the weekend. It's definitely possible but I'm fairly sure we would need to do polling in a vercel cron with a personal access token. Just have to be careful about rate limits.
> 
> I'm not sure we can reply to webhooks instantly without creating a bot, like the vercel one. But if we did that, then we'd have to have permissions to add it to every repo instead of being able to grab any and all PR's or issues on any repo, like we can now. The commits would also be from the bot instead of our own account.
> 
> [revise.dev](https://revise.dev/) that Josh Pigford is working on takes the bot strategy in a similar product. So, to me, it seems like a core differentiator would be keeping it so the commits come from our own accounts so we can push changes anywhere

**Comment by slavingia** [comment]
Look at GitHub bots like dependabot etc, which people are already familiar with. It would be really cool to spin up a feature branch PR, and then once it's green, auto merge into the main branch
