### ISSUE TITLE
breakdown tdd?

### ISSUE THREAD

**Issue by juniusfree** [anti-work/shortest#71]
I'm just throwing out an idea related to https://github.com/anti-work/shortest/issues/37

What if, instead of asking the model to go straight from plain English instructions to a full unit test, we broke the TDD process into smaller steps and implemented/tested them separately? [This tweet](https://x.com/snowmaker/status/1843015916050948372) mentioned that this approach helped CaseText, and [this blog](https://medium.com/@benjamin22-314/automating-test-driven-development-with-llms-c05e7a3cdfe1) noted that modular LLM tasks are easier to test.

For example, the first step in TDD is to [define a test list](https://tidyfirst.substack.com/p/canon-tdd). Instead of asking the LLM to generate a full test from plain English like “create a login feature,” we could start by using a dedicated LLM module to create a detailed [given-when-then scenario](https://martinfowler.com/bliki/GivenWhenThen.html), such as: *Given the user enters their username and password, when they click login, then they should see their dashboard.* We could then validate this module with [hundreds of tests](https://x.com/snowmaker/status/1843015921000149129) to ensure it meets the required standard for this TDD step. This same method could be applied to other steps, and we could even break it down further into more granular steps.

This approach may seem too detailed, and I’m no expert on this, but I’m interested in exploring if this will produce a more reliable result. What do you think, @slavingia?

**Comment by slavingia** [comment]
Sounds interesting

**Comment by slavingia** [comment]
Feel free to take a stab, seems more relevant for AI evals than product feature development though
